; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules

projects[views_bulk_operations][version] = "3.2"
projects[admin_menu][version] = "3.0-rc4"
projects[adminimal_admin_menu][version] = "1.4"
projects[amazons3][version] = "1.x-dev"
projects[awssdk][version] = "5.x-dev"
projects[backup_migrate][version] = "2.8"
projects[block_class][version] = "2.1"
projects[book_delete][version] = "1.x-dev"
projects[bookblock][version] = "1.x-dev"
projects[ctools][version] = "1.4"
projects[ckeditor][version] = "1.x-dev"
projects[computed_field][version] = "1.0"
projects[content_menu][version] = "1.0"
projects[context][version] = "3.1"
projects[date][version] = "2.7"
projects[delete_all][version] = "1.x-dev"
projects[deploy][version] = "2.x-dev"
projects[devel][version] = "1.x-dev"
projects[diff][version] = "3.x-dev"
projects[ds][version] = "2.6"
projects[entity][version] = "1.2"
projects[entity_dependency][version] = "1.x-dev"
projects[entityreference][version] = "1.1"
projects[entityreference_feeds][version] = "1.0-beta1"
projects[eva][version] = "1.x-dev"
projects[features][version] = "2.0"
projects[features_override][version] = "2.0-rc1"
projects[feeds][version] = "2.x-dev"
projects[feeds_entityreference][version] = "1.x-dev"
projects[feeds_node_helper][version] = "1.x-dev"
projects[feeds_tamper][version] = "1.0-beta5"
projects[feeds_tamper_string2id][version] = "1.0"
projects[feeds_xpathparser][version] = "1.0-beta4"
projects[file_entity][version] = "2.0-alpha3"
projects[formblock][version] = "1.x-dev"
projects[ftools][version] = "2.x-dev"
projects[hidden_nodes][version] = "1.1"
projects[imce][version] = "1.8"
projects[imce_mkdir][version] = "1.x-dev"
projects[job_scheduler][version] = "2.x-dev"
projects[jquery_update][version] = "2.x-dev"
projects[libraries][version] = "3.x-dev"
projects[lightbox2][version] = "1.x-dev"
projects[link][version] = "1.2"
projects[linkit][version] = "3.1"
projects[menu_editor][version] = "1.x-dev"
projects[media][version] = "2.0-alpha3"
projects[menu_block][version] = "3.x-dev"
projects[menu_item_visibility][version] = "1.x-dev"
projects[menu_position][version] = "2.x-dev"
projects[menu_token][version] = "1.0-beta5"
projects[module_filter][version] = "2.0-alpha2"
projects[multiform][version] = "1.x-dev"
projects[node_export][version] = "3.x-dev"
projects[outline_designer][version] = "2.0-rc3"
projects[overlay_paths][version] = "1.3"
projects[panels][version] = "3.x-dev"
projects[path_alias_xt][version] = "1.1"
projects[pathauto][version] = "1.x-dev"
projects[quickbar][version] = "2.x-dev"
projects[quicktabs][version] = "3.6"
projects[services][version] = "3.5"
projects[semanticviews][version] = "1.x-dev"
projects[taxonomy_menu][version] = "2.x-dev"
projects[taxonomy_csv][version] = "5.x-dev"
projects[token][version] = "1.5"
projects[uuid][version] = "1.x-dev"
projects[views][version] = "3.x-dev"
projects[views_php][version] = "1.x-dev"
projects[views_slideshow][version] = "3.1"
projects[views_slideshow_xtra][version] = "3.x-dev"
projects[views_tree][version] = "2.x-dev"
; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nasa_science][download][type] = ""
projects[nasa_science][download][url] = ""
projects[nasa_science][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[science_nasa][download][type] = ""
projects[science_nasa][download][url] = ""
projects[science_nasa][type] = "theme"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nasascience_customization_feature][download][type] = ""
projects[nasascience_customization_feature][download][url] = ""
projects[nasascience_customization_feature][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[html_encoder][download][type] = ""
libraries[html_encoder][download][url] = ""
libraries[html_encoder][directory_name] = "html_encoder"
libraries[html_encoder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.blockui][download][type] = ""
libraries[jquery.blockui][download][url] = ""
libraries[jquery.blockui][directory_name] = "jquery.blockui"
libraries[jquery.blockui][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[awssdk][download][type] = ""
libraries[awssdk][download][url] = ""
libraries[awssdk][directory_name] = "awssdk"
libraries[awssdk][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jcarousel][download][type] = ""
libraries[jcarousel][download][url] = ""
libraries[jcarousel][directory_name] = "jcarousel"
libraries[jcarousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = ""
libraries[plupload][download][url] = ""
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

